source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ALMediaLibrary_Example', :exclusive => true do
  pod "ALMediaLibrary", :path => "../"
end

target 'ALMediaLibrary_Tests', :exclusive => true do
  pod "ALMediaLibrary", :path => "../"

  
end
